### ISSUE TITLE
Feature request: delay

### ISSUE THREAD

**Issue by leegee** [mmurph211/Autocomplete#1]
My server search is a bit heavy, so I only want to have it called a few seconds after the user has stopped typing. Would you consider adding that feature?

**Comment by mmurph211** [comment]
Hi leegee,

You can do this today by using a timer that overwrites itself as the user keeps typing. An example:

```
var throttler;

new Autocomplete("myInput", {
    srcType : "dom", 
    onInput : function(newValue, oldValue) {
        var autocomplete = this;

        throttler = (throttler) ? window.clearTimeout(throttler) : null;
        throttler = window.setTimeout(function() {
            sendAjaxRequest(newValue, function(values) {
                // Execute callback:
                autocomplete.addValues(values);
            });
        }, 2500); // Wait a few seconds
    }
});
```

**Comment by leegee** [comment]
Hi Matt,

That's what I'm doing, but it seems such a basic feature, it would 
really nice to have it built in to this otherwise perfect library!

Thanksfor writing
Lee

**Comment by mmurph211** [comment]
Thank you for the compliment. Agreed this would be a good enhancement.

**Comment by mmurph211** [comment]
Closing as completed.
